/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tulskiy_musique_audio_formats_aac_libfaad2_jlibfaad */

#ifndef _Included_com_tulskiy_musique_audio_formats_aac_libjfaad_libjfaad
#define _Included_com_tulskiy_musique_audio_formats_aac_libjfaad_libjfaad
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tulskiy_musique_audio_formats_aac_libjfaad_libjfaad
 * Method:    open
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jint JNICALL Java_com_tulskiy_musique_audio_formats_aac_libjfaad_libjfaad_open
  (JNIEnv *, jobject, jstring);

JNIEXPORT jint JNICALL Java_com_tulskiy_musique_audio_formats_aac_libjfaad_libjfaad_getSampleRate
  (JNIEnv *, jobject, jint);

JNIEXPORT jint JNICALL Java_com_tulskiy_musique_audio_formats_aac_libjfaad_libjfaad_getChannels
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_tulskiy_musique_audio_formats_aac_libjfaad_libjfaad
 * Method:    decode
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_tulskiy_musique_audio_formats_aac_libjfaad_libjfaad_decode
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     com_tulskiy_musique_audio_formats_aac_libjfaad_libjfaad
 * Method:    seek
 * Signature: (J)V
 */
JNIEXPORT jint JNICALL Java_com_tulskiy_musique_audio_formats_aac_libjfaad_libjfaad_seek
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     com_tulskiy_musique_audio_formats_aac_libjfaad_libjfaad
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT jint JNICALL Java_com_tulskiy_musique_audio_formats_aac_libjfaad_libjfaad_close
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
